services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metrics-front
    ports:
      - "4200:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
